apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: hello-world
    chart: {{ template "hello-world-chart.chart" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: hello-world
    release: {{ .Release.Name }}
